# Generated by Django 4.2.3 on 2023-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='form_images')),
                ('bio', models.TextField()),
            ],
        ),
    ]
