# Generated by Django 4.2.3 on 2023-09-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Female', max_length=20),
            preserve_default=False,
        ),
    ]
