# Generated by Django 4.2.4 on 2023-09-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
