# Generated by Django 4.2.4 on 2023-09-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='markerTitle',
        ),
    ]
