# Generated by Django 4.2.3 on 2023-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_title_location_markertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
    ]
