# Generated by Django 4.2.4 on 2023-09-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_rename_payment_amount_payment_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_payment_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
