# Generated by Django 4.2.4 on 2023-09-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_rename_order_payment_id_payment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=500)),
                ('medium', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(upload_to='form_images')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
