# Generated by Django 4.2.4 on 2023-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_artwork_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='form_images'),
        ),
    ]
