# Generated by Django 4.2.4 on 2023-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fname',
            field=models.CharField(default='Artist', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.CharField(default='Artwork Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=25),
        ),
    ]
