# Generated by Django 4.2.4 on 2023-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_payment_fname_payment_title_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
