# Generated by Django 4.2.4 on 2023-09-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
